#!/bin/bash

# Modm - Modules iMproved
# Copyright (C) 2013-2014  Michael Schlottke
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# This is a bash autocompleter function for the modm subcommands
_modm()
{
  # Create local variables
  local cur prev subcommands

  # Reset return variable
  COMPREPLY=()

  # Parse previous options
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"

  # Set list of subcommands
  subcommands="avail config help list load unload"

  # Complete the argument
  COMPREPLY=($(compgen -W "${subcommands}" -- ${cur}))

  # Return success
  return 0
}

# Register function for modm
complete -F _modm modm
